name: Node.js CI

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

env:
  DATABASE_URL: mysql://root:Lumieresmysql6993+@localhost:3306/pfetest
  DB_PORT: 3306
  DB_HOST: localhost
  DB_USERNAME: root
  DB_PASSWORD: Lumieresmysql6993+
  DB_NAME: pfe

  ACCESS_TOKEN: 1d2342ed0f209630f23b0aa56314751cb7e5025cde49fafc5473f18a9e734a4ebbf2970607c899fd043758e94180bfd2dee8e48509e0d13d3cd49151b815115c

  EMAIL: a_phothirath@etu-webschoolfactory.fr
  PASSWORD: vmPczYqP

  GUEST: guest

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            mysql-version: 8.0

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: ./.
        with:
          mysql-version: ${{ matrix.mysql-version }}
          database: ${{ env.DB_NAME }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test
